# If false, only pilots can enter vehicles
Allow-Anyone-To-Enter-Vehicles: true
# The plugin will still announce if the Flag was captured
Announce-War-End-Cause-To-All-Players: true
Hyped-Up-On-Lemonade-And-Gummy-Worms: false