name: WorldWar
version: 0.0.5
main: io.github.podshot.WorldWar
description: World War Plugin

commands:
      ww:
           description: World War Command
           usage: /<command> start
           permission: ww.start
           permussion-message: You don't have <permission>
      test:
           description: Test Command
           usage: /<command> [arguments]

permissions:
      ww.start:
                description: All World War Commands
                default: true