name: WorldWar
version: 0.0.6
main: io.github.podshot.WorldWar
description: World War Plugin

commands:
      worldwar:
           description: World War Command
           usage: /<command> start
           permission: ww.start
           permussion-message: You don't have <permission>
      test:
           description: Test Command
           usage: /<command> [arguments]
      squad:
           description: Squad Command
           usage: /<command> [arguments]
      team:
        description: Team Command
        usage: /<command> [arguments]

permissions:
      ww.start:
                description: All World War Commands
                default: true